### ISSUE TITLE
"Unable to Set Up Repo - Marisa67

### ISSUE THREAD

**Issue by Marisa67** [uwhpsc-2016/syllabus#19]
Still no go.

**Comment by quantheory** [comment]
Sometimes it creates an error message even though it actually works. The following repo seems to have been created:

https://github.com/uwhpsc-2016/homework1-Marisa67

Does this work for you?

**Comment by Marisa67** [comment]
Should it work if I just click on it? If I click on it,  it says that This is not the web page I'm looking for.

**Comment by Marisa67** [comment]
~$ git clone https://github.com/uwhpsc-2016/homework1-Marisa67

Cloning into 'homework1-Marisa67'...

Username for 'https://github.com': Marisa67

Password for 'https://Marisa67@github.com':

remote: Repository not found.

fatal: repository 'https://github.com/uwhpsc-2016/homework1-Marisa67/' not found

This did not work either.

**Comment by quantheory** [comment]
It appears that it created a repo, but you don't have permission to view that repo. There seems to be another student with the same issue...

**Comment by Marisa67** [comment]
Now I get the message that there is already a repo created with that name, but still I can't see it.

**Comment by quantheory** [comment]
That's correct; the repo exists, but for some reason you don't have permission to view it. @cswiercz will have to fix this.

**Comment by gluckt** [comment]
Seems like I have the same problem. Guess we just have to wait for a fix.

**Comment by cswiercz** [comment]
@Marisa67 Try this URL now: https://github.com/uwhpsc-2016/homework1-Marisa67 Let me know if it works by closing this issue.

**Comment by Marisa67** [comment]
Thank you!
