### ISSUE TITLE
Unable to Set Up Repo - LaTournesol

### ISSUE THREAD

**Issue by LaTournesol** [uwhpsc-2016/syllabus#20]
github user name: LaTournesol
Thanks!

**Comment by mvelegar** [comment]
@LaTournesol : I can't seem to find that repository, so it hasn't been created. Could you please try creating it again? We have followed instructions from GitHub folks, it may have taken care of the error you got previously.

**Comment by LaTournesol** [comment]
Thanks mvelegar! It's working now, I have the private repo.
