### ISSUE TITLE
Unable to setup Repo- krvikassingh

### ISSUE THREAD

**Issue by krvikassingh** [uwhpsc-2016/syllabus#21]
I open an issue as describe in your email and got this back from GitHub community. 

username: krvikassingh
## Thank You

Vikas

" Hi Vikas,

If you are still experiencing this issue please have your instructor log out of Classroom for GitHub, then log back in. If the issue persists then your instructor should open an issue here:

https://github.com/education/classroom/issues"

**Comment by mvelegar** [comment]
@krvikassingh : Try navigating here now: https://github.com/uwhpsc-2016/homework1-krvikassingh. Let us know if that works!

**Comment by krvikassingh** [comment]
@mvelegar this is what I am getting 

remote: Repository not found.
fatal: repository 'https://github.com/uwhpsc-2016/homework1-krvikassingh/' not found

**Comment by mvelegar** [comment]
@krvikassingh : The repository does exist, again you are not able to see it. @cswiercz could you please help, maybe I did it incorrectly.

**Comment by krvikassingh** [comment]
Got it 
Thanks
