### ISSUE TITLE
Homework 1 Repository

### ISSUE THREAD

**Issue by LepcisMagna** [uwhpsc-2016/syllabus#28]
The link for the Homework 1 repository is not working - it sounds like it got created but did not entitle the permissions correctly.  The GitHub Classroom folks [suggest](https://github.com/education/classroom/issues/560) deleting my fork on your end at which point I should be able to re-create it.  Thank you!

**Comment by cswiercz** [comment]
Not sure what happened during the creation process. I've granted you permissions to https://github.com/uwhpsc-2016/homework1-LepcisMagna . Try now and let me know if it works.

**Comment by LepcisMagna** [comment]
It works!  Thank you.
