### ISSUE TITLE
April Fools - Final Exam Structure 

### ISSUE THREAD

**Issue by jlombs** [uwhpsc-2016/syllabus#7]
Hi Chris/Everyone, 

I have to say, I strongly disagree with the idea that 100% of our course grade should be mandatorily based on a final exam. I'm really not sure what you are accomplishing by that, given that you'll probably still have scheduling conflicts for the written part of the final period anyway. Our goal is to be able to demonstrate our accumulated knowledge to you, but I fail to see how forcing that into a one-shot timed assessment is genuinely testing what we have learned. 

Speaking for the graduate students, the aim of a course like this is to be able to gather useful skills to aid in our research or future careers, and rarely does the sum total of our hard work depend on what we happen to be able to recall in a half hour on one particular day. If someone is sick, or having an off day, or is like myself and has a rough time with test anxiety, you are really crippling their ability to show you what they have learned throughout the quarter and have it count for something, especially for a written test on programming when often the most creative and optimal solutions come from sleeping on a problem and tinkering with algorithms. 

I truly hope you reconsider this new policy.  If anything, I'd suggest making the written part of the final optional to those students who have participated thoroughly throughout the course and have done all the quizzes and homeworks, and mandatory in the opposite case for students who would rather get it all over bandaid style (while we all complete the project element of the final, given that an extended project is arguably the best way to illustrate our amassed course knowledge independent of testing parameters). 

Best, 

John

**Comment by cswiercz** [comment]
@jlombs See here: https://canvas.uw.edu/courses/1038251/discussion_topics/3292614

**Comment by cswiercz** [comment]
> Speaking for the graduate students, the aim of a course like this is to be able to gather useful skills to aid in our research or future careers, and rarely does the sum total of our hard work depend on what we happen to be able to recall in a half hour on one particular day. If someone is sick, or having an off day, or is like myself and has a rough time with test anxiety, you are really crippling their ability to show you what they have learned throughout the quarter and have it count for something, especially for a written test on programming when often the most creative and optimal solutions come from sleeping on a problem and tinkering with algorithms.

I would like to add that I completely agree with this assessment. Much is learned when taking the time to mull over a problem, roll it around in your head, and explore all possible avenues to a solution.
